### PR TITLE
1463 add courses fees page

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
Re-creating `/organisation/2cf/course/self/2yn6/fees` in rails

### Changes proposed in this pull request
Add `/fees` to a course

c# | rails
:--:|:--:
c#|rails

### CODE REVIEW

**Comment by dankmitchell** [comment]
[Add edit course length and fees page](https://trello.com/c/qrMfyr7Q/1463-add-edit-course-length-and-fees-page)

**Comment by benilovj** [comment]
In the Rails screenshot, the fee is "9000.0" (extra zero)... will that be resolved with the backend work?

**Comment by dankmitchell** [comment]
@misaka do you think I should edit the backend to return a rounded number amount? Or make the frontend do it?

**Comment by benilovj** [comment]
> @misaka do you think I should edit the backend to return a rounded number amount? Or make the frontend do it?

Just discussed it with @misaka IRL, we've come to the conclusion that the frontend should explicitly define how it formats the number, even if it comes through in the right format from the backend.

**Pull request merged**
