### PR TITLE
[1495] Change add location button to link to form

### PR DESCRIPTION
**Pull request by tvararu**
### Context

Hooks up the form created in https://github.com/DFE-Digital/manage-courses-frontend/pull/283.

To be rebased and merged after that.

### CODE REVIEW

**Comment by tvararu** [comment]
[Hook up add new location form](https://trello.com/c/bq14MJUf/1495-hook-up-add-new-location-form)

**Comment by tvararu** [comment]
Adding a WIP while we wait to merge this.

**Comment by tvararu** [comment]
When users have more locations than the maximum number of location codes, we should disable the button. Going to add that now.

**Comment by tvararu** [comment]
When provider has maxed out sites:

Screen Shot 2019-05-17 at 16 38 07

**Comment by tvararu** [comment]
[Publishers shouldn't be able to add more than 37 training locations](https://trello.com/c/1HgAUmLX/1497-publishers-shouldnt-be-able-to-add-more-than-37-training-locations)

**Comment by misaka** [comment]
@tvararu Just to check, is this still a WIP?

**Comment by benilovj** [comment]
@misaka it’s wip until we release backend. We don’t want to couple frontend and backend unnecessarily.

**Comment by misaka** [comment]
Might be nice to have a "do not merge" label.

**Comment by tvararu** [comment]
@misaka ✅

**Pull request merged**
